"""Add habit tracker tables

Revision ID: b4bfcecf23f3
Revises: d0583ca94185
Create Date: 2026-02-15 13:58:30.413593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bfcecf23f3'
down_revision: Union[str, Sequence[str], None] = 'd0583ca94185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_challenges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('challenge_type', sa.Enum('STREAK', 'COUNT', 'PERFECT_DAY', name='challengetype'), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('WEEKLY', 'MONTHLY', name='challengeperiod'), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habit_badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_type', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_badges_badge_type'), 'habit_badges', ['badge_type'], unique=False)
    op.create_index(op.f('ix_habit_badges_user_id'), 'habit_badges', ['user_id'], unique=False)
    op.create_table('habit_challenge_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['habit_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_challenge_progress_challenge_id'), 'habit_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_habit_challenge_progress_user_id'), 'habit_challenge_progress', ['user_id'], unique=False)
    op.create_table('habits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('habit_type', sa.Enum('POSITIVE', 'NEGATIVE', name='habittype'), nullable=False),
    sa.Column('frequency_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='frequencytype'), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habits_user_id'), 'habits', ['user_id'], unique=False)
    op.create_table('habit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('habit_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_habit_logs_habit_id'), 'habit_logs', ['habit_id'], unique=False)
    op.create_index(op.f('ix_habit_logs_logged_date'), 'habit_logs', ['logged_date'], unique=False)
    op.create_index(op.f('ix_habit_logs_user_id'), 'habit_logs', ['user_id'], unique=False)
    op.add_column('users', sa.Column('habit_xp', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'habit_xp')
    op.drop_index(op.f('ix_habit_logs_user_id'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_logged_date'), table_name='habit_logs')
    op.drop_index(op.f('ix_habit_logs_habit_id'), table_name='habit_logs')
    op.drop_table('habit_logs')
    op.drop_index(op.f('ix_habits_user_id'), table_name='habits')
    op.drop_table('habits')
    op.drop_index(op.f('ix_habit_challenge_progress_user_id'), table_name='habit_challenge_progress')
    op.drop_index(op.f('ix_habit_challenge_progress_challenge_id'), table_name='habit_challenge_progress')
    op.drop_table('habit_challenge_progress')
    op.drop_index(op.f('ix_habit_badges_user_id'), table_name='habit_badges')
    op.drop_index(op.f('ix_habit_badges_badge_type'), table_name='habit_badges')
    op.drop_table('habit_badges')
    op.drop_table('habit_challenges')
    # ### end Alembic commands ###
