"""Add location field to users

Revision ID: d0583ca94185
Revises: 9f0f78f14cf8
Create Date: 2026-02-15 13:23:56.105258

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d0583ca94185"
down_revision: Union[str, Sequence[str], None] = "9f0f78f14cf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("location", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "location")
    # ### end Alembic commands ###
